#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : mailimporter
Version  : 18.08.0
Release  : 1
URL      : https://download.kde.org/stable/applications/18.08.0/src/mailimporter-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/mailimporter-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/mailimporter-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: mailimporter-lib
Requires: mailimporter-license
Requires: mailimporter-locales
BuildRequires : akonadi-dev
BuildRequires : akonadi-mime-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kmime-dev
BuildRequires : libkdepim-dev
BuildRequires : qtbase-dev qtbase-extras mesa-dev

%description
No detailed description available

%package dev
Summary: dev components for the mailimporter package.
Group: Development
Requires: mailimporter-lib
Provides: mailimporter-devel

%description dev
dev components for the mailimporter package.


%package lib
Summary: lib components for the mailimporter package.
Group: Libraries
Requires: mailimporter-license

%description lib
lib components for the mailimporter package.


%package license
Summary: license components for the mailimporter package.
Group: Default

%description license
license components for the mailimporter package.


%package locales
Summary: locales components for the mailimporter package.
Group: Default

%description locales
locales components for the mailimporter package.


%prep
%setup -q -n mailimporter-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535265077
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535265077
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/mailimporter
cp COPYING %{buildroot}/usr/share/doc/mailimporter/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/mailimporter/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang libmailimporter

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/MailImporter/FilterBalsa
/usr/include/KF5/MailImporter/FilterClawsMail
/usr/include/KF5/MailImporter/FilterEvolution
/usr/include/KF5/MailImporter/FilterEvolution_v2
/usr/include/KF5/MailImporter/FilterEvolution_v3
/usr/include/KF5/MailImporter/FilterIcedove
/usr/include/KF5/MailImporter/FilterImporterBase
/usr/include/KF5/MailImporter/FilterInfo
/usr/include/KF5/MailImporter/FilterInfoGui
/usr/include/KF5/MailImporter/FilterKMailArchive
/usr/include/KF5/MailImporter/FilterKMail_maildir
/usr/include/KF5/MailImporter/FilterLNotes
/usr/include/KF5/MailImporter/FilterMBox
/usr/include/KF5/MailImporter/FilterMailApp
/usr/include/KF5/MailImporter/FilterMailmanGzip
/usr/include/KF5/MailImporter/FilterOE
/usr/include/KF5/MailImporter/FilterOpera
/usr/include/KF5/MailImporter/FilterPMail
/usr/include/KF5/MailImporter/FilterPlain
/usr/include/KF5/MailImporter/FilterSeaMonkey
/usr/include/KF5/MailImporter/FilterSylpheed
/usr/include/KF5/MailImporter/FilterTheBat
/usr/include/KF5/MailImporter/FilterThunderbird
/usr/include/KF5/MailImporter/Filters
/usr/include/KF5/MailImporter/ImportMailsWidget
/usr/include/KF5/MailImporter/MailImporter_Utils
/usr/include/KF5/MailImporter/MessageStatus
/usr/include/KF5/MailImporter/OtherMailerUtil
/usr/include/KF5/MailImporterAkonadi/FilterImporterAkonadi
/usr/include/KF5/mailimporter/filterbalsa.h
/usr/include/KF5/mailimporter/filterclawsmail.h
/usr/include/KF5/mailimporter/filterevolution.h
/usr/include/KF5/mailimporter/filterevolution_v2.h
/usr/include/KF5/mailimporter/filterevolution_v3.h
/usr/include/KF5/mailimporter/filtericedove.h
/usr/include/KF5/mailimporter/filterimporterbase.h
/usr/include/KF5/mailimporter/filterinfo.h
/usr/include/KF5/mailimporter/filterinfogui.h
/usr/include/KF5/mailimporter/filterkmail_maildir.h
/usr/include/KF5/mailimporter/filterkmailarchive.h
/usr/include/KF5/mailimporter/filterlnotes.h
/usr/include/KF5/mailimporter/filtermailapp.h
/usr/include/KF5/mailimporter/filtermailmangzip.h
/usr/include/KF5/mailimporter/filtermbox.h
/usr/include/KF5/mailimporter/filteroe.h
/usr/include/KF5/mailimporter/filteropera.h
/usr/include/KF5/mailimporter/filterplain.h
/usr/include/KF5/mailimporter/filterpmail.h
/usr/include/KF5/mailimporter/filters.h
/usr/include/KF5/mailimporter/filterseamonkey.h
/usr/include/KF5/mailimporter/filtersylpheed.h
/usr/include/KF5/mailimporter/filterthebat.h
/usr/include/KF5/mailimporter/filterthunderbird.h
/usr/include/KF5/mailimporter/importmailswidget.h
/usr/include/KF5/mailimporter/mailimporter_export.h
/usr/include/KF5/mailimporter/mailimporter_utils.h
/usr/include/KF5/mailimporter/messagestatus.h
/usr/include/KF5/mailimporter/othermailerutil.h
/usr/include/KF5/mailimporter_version.h
/usr/include/KF5/mailimporterakonadi/filterimporterakonadi.h
/usr/include/KF5/mailimporterakonadi/mailimporterakonadi_export.h
/usr/include/KF5/mailimporterakonadi_version.h
/usr/lib64/cmake/KF5MailImporter/KF5MailImporterConfig.cmake
/usr/lib64/cmake/KF5MailImporter/KF5MailImporterConfigVersion.cmake
/usr/lib64/cmake/KF5MailImporter/KF5MailImporterTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5MailImporter/KF5MailImporterTargets.cmake
/usr/lib64/cmake/KF5MailImporterAkonadi/KF5MailImporterAkonadiConfig.cmake
/usr/lib64/cmake/KF5MailImporterAkonadi/KF5MailImporterAkonadiConfigVersion.cmake
/usr/lib64/cmake/KF5MailImporterAkonadi/KF5MailImporterAkonadiTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5MailImporterAkonadi/KF5MailImporterAkonadiTargets.cmake
/usr/lib64/libKF5MailImporter.so
/usr/lib64/libKF5MailImporterAkonadi.so
/usr/lib64/qt5/mkspecs/modules/qt_MailImporter.pri
/usr/lib64/qt5/mkspecs/modules/qt_MailImporterAkonadi.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5MailImporter.so.5
/usr/lib64/libKF5MailImporter.so.5.9.0
/usr/lib64/libKF5MailImporterAkonadi.so.5
/usr/lib64/libKF5MailImporterAkonadi.so.5.9.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/mailimporter/COPYING
/usr/share/doc/mailimporter/COPYING.LIB

%files locales -f libmailimporter.lang
%defattr(-,root,root,-)

