#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v12
# autospec commit: fbcebd0
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : mailimporter
Version  : 24.05.1
Release  : 68
URL      : https://download.kde.org/stable/release-service/24.05.1/src/mailimporter-24.05.1.tar.xz
Source0  : https://download.kde.org/stable/release-service/24.05.1/src/mailimporter-24.05.1.tar.xz
Source1  : https://download.kde.org/stable/release-service/24.05.1/src/mailimporter-24.05.1.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0
Requires: mailimporter-data = %{version}-%{release}
Requires: mailimporter-lib = %{version}-%{release}
Requires: mailimporter-license = %{version}-%{release}
Requires: mailimporter-locales = %{version}-%{release}
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : akonadi-mime-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : grantlee-dev
BuildRequires : grantleetheme-dev
BuildRequires : kcontacts-dev
BuildRequires : kimap-dev
BuildRequires : kimap-staticdev
BuildRequires : kmime-dev
BuildRequires : kpimtextedit-dev
BuildRequires : ktextaddons-dev
BuildRequires : pimcommon-dev
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package data
Summary: data components for the mailimporter package.
Group: Data

%description data
data components for the mailimporter package.


%package dev
Summary: dev components for the mailimporter package.
Group: Development
Requires: mailimporter-lib = %{version}-%{release}
Requires: mailimporter-data = %{version}-%{release}
Provides: mailimporter-devel = %{version}-%{release}
Requires: mailimporter = %{version}-%{release}

%description dev
dev components for the mailimporter package.


%package lib
Summary: lib components for the mailimporter package.
Group: Libraries
Requires: mailimporter-data = %{version}-%{release}
Requires: mailimporter-license = %{version}-%{release}

%description lib
lib components for the mailimporter package.


%package license
Summary: license components for the mailimporter package.
Group: Default

%description license
license components for the mailimporter package.


%package locales
Summary: locales components for the mailimporter package.
Group: Default

%description locales
locales components for the mailimporter package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n mailimporter-24.05.1
cd %{_builddir}/mailimporter-24.05.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1718569273
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DQT_MAJOR_VERSION=6  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DQT_MAJOR_VERSION=6  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1718569273
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mailimporter
cp %{_builddir}/mailimporter-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/mailimporter/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/mailimporter/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/mailimporter/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/mailimporter/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/mailimporter/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/mailimporter/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/mailimporter/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/mailimporter/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/mailimporter-%{version}/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/mailimporter/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang libmailimporter6
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qlogging-categories6/mailimporter.categories
/usr/share/qlogging-categories6/mailimporter.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KPim6/MailImporter/MailImporter/FilterBalsa
/usr/include/KPim6/MailImporter/MailImporter/FilterClawsMail
/usr/include/KPim6/MailImporter/MailImporter/FilterEvolution
/usr/include/KPim6/MailImporter/MailImporter/FilterEvolution_v2
/usr/include/KPim6/MailImporter/MailImporter/FilterEvolution_v3
/usr/include/KPim6/MailImporter/MailImporter/FilterIcedove
/usr/include/KPim6/MailImporter/MailImporter/FilterImporterBase
/usr/include/KPim6/MailImporter/MailImporter/FilterInfo
/usr/include/KPim6/MailImporter/MailImporter/FilterInfoGui
/usr/include/KPim6/MailImporter/MailImporter/FilterKMailArchive
/usr/include/KPim6/MailImporter/MailImporter/FilterKMail_maildir
/usr/include/KPim6/MailImporter/MailImporter/FilterLNotes
/usr/include/KPim6/MailImporter/MailImporter/FilterMBox
/usr/include/KPim6/MailImporter/MailImporter/FilterMailApp
/usr/include/KPim6/MailImporter/MailImporter/FilterMailmanGzip
/usr/include/KPim6/MailImporter/MailImporter/FilterOE
/usr/include/KPim6/MailImporter/MailImporter/FilterOpera
/usr/include/KPim6/MailImporter/MailImporter/FilterPMail
/usr/include/KPim6/MailImporter/MailImporter/FilterPlain
/usr/include/KPim6/MailImporter/MailImporter/FilterSeaMonkey
/usr/include/KPim6/MailImporter/MailImporter/FilterSylpheed
/usr/include/KPim6/MailImporter/MailImporter/FilterTheBat
/usr/include/KPim6/MailImporter/MailImporter/FilterThunderbird
/usr/include/KPim6/MailImporter/MailImporter/Filters
/usr/include/KPim6/MailImporter/MailImporter/ImportMailsWidget
/usr/include/KPim6/MailImporter/MailImporter/MailImporter_Utils
/usr/include/KPim6/MailImporter/MailImporter/MessageStatus
/usr/include/KPim6/MailImporter/MailImporter/OtherMailerUtil
/usr/include/KPim6/MailImporter/mailimporter/filterbalsa.h
/usr/include/KPim6/MailImporter/mailimporter/filterclawsmail.h
/usr/include/KPim6/MailImporter/mailimporter/filterevolution.h
/usr/include/KPim6/MailImporter/mailimporter/filterevolution_v2.h
/usr/include/KPim6/MailImporter/mailimporter/filterevolution_v3.h
/usr/include/KPim6/MailImporter/mailimporter/filtericedove.h
/usr/include/KPim6/MailImporter/mailimporter/filterimporterbase.h
/usr/include/KPim6/MailImporter/mailimporter/filterinfo.h
/usr/include/KPim6/MailImporter/mailimporter/filterinfogui.h
/usr/include/KPim6/MailImporter/mailimporter/filterkmail_maildir.h
/usr/include/KPim6/MailImporter/mailimporter/filterkmailarchive.h
/usr/include/KPim6/MailImporter/mailimporter/filterlnotes.h
/usr/include/KPim6/MailImporter/mailimporter/filtermailapp.h
/usr/include/KPim6/MailImporter/mailimporter/filtermailmangzip.h
/usr/include/KPim6/MailImporter/mailimporter/filtermbox.h
/usr/include/KPim6/MailImporter/mailimporter/filteroe.h
/usr/include/KPim6/MailImporter/mailimporter/filteropera.h
/usr/include/KPim6/MailImporter/mailimporter/filterplain.h
/usr/include/KPim6/MailImporter/mailimporter/filterpmail.h
/usr/include/KPim6/MailImporter/mailimporter/filters.h
/usr/include/KPim6/MailImporter/mailimporter/filterseamonkey.h
/usr/include/KPim6/MailImporter/mailimporter/filtersylpheed.h
/usr/include/KPim6/MailImporter/mailimporter/filterthebat.h
/usr/include/KPim6/MailImporter/mailimporter/filterthunderbird.h
/usr/include/KPim6/MailImporter/mailimporter/importmailswidget.h
/usr/include/KPim6/MailImporter/mailimporter/mailimporter_export.h
/usr/include/KPim6/MailImporter/mailimporter/mailimporter_utils.h
/usr/include/KPim6/MailImporter/mailimporter/messagestatus.h
/usr/include/KPim6/MailImporter/mailimporter/othermailerutil.h
/usr/include/KPim6/MailImporter/mailimporter_version.h
/usr/include/KPim6/MailImporterAkonadi/MailImporterAkonadi/FilterImporterAkonadi
/usr/include/KPim6/MailImporterAkonadi/mailimporterakonadi/filterimporterakonadi.h
/usr/include/KPim6/MailImporterAkonadi/mailimporterakonadi/mailimporterakonadi_export.h
/usr/include/KPim6/MailImporterAkonadi/mailimporterakonadi_version.h
/usr/lib64/cmake/KPim6MailImporter/KPim6MailImporterConfig.cmake
/usr/lib64/cmake/KPim6MailImporter/KPim6MailImporterConfigVersion.cmake
/usr/lib64/cmake/KPim6MailImporter/KPim6MailImporterTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim6MailImporter/KPim6MailImporterTargets.cmake
/usr/lib64/cmake/KPim6MailImporterAkonadi/KPim6MailImporterAkonadiConfig.cmake
/usr/lib64/cmake/KPim6MailImporterAkonadi/KPim6MailImporterAkonadiConfigVersion.cmake
/usr/lib64/cmake/KPim6MailImporterAkonadi/KPim6MailImporterAkonadiTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim6MailImporterAkonadi/KPim6MailImporterAkonadiTargets.cmake
/usr/lib64/libKPim6MailImporter.so
/usr/lib64/libKPim6MailImporterAkonadi.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKPim6MailImporter.so.6.1.1
/V3/usr/lib64/libKPim6MailImporterAkonadi.so.6.1.1
/usr/lib64/libKPim6MailImporter.so.6
/usr/lib64/libKPim6MailImporter.so.6.1.1
/usr/lib64/libKPim6MailImporterAkonadi.so.6
/usr/lib64/libKPim6MailImporterAkonadi.so.6.1.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mailimporter/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/mailimporter/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/mailimporter/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/mailimporter/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/mailimporter/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4
/usr/share/package-licenses/mailimporter/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/mailimporter/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/mailimporter/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f libmailimporter6.lang
%defattr(-,root,root,-)

