#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : mailimporter
Version  : 23.04.0
Release  : 52
URL      : https://download.kde.org/stable/release-service/23.04.0/src/mailimporter-23.04.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/23.04.0/src/mailimporter-23.04.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/23.04.0/src/mailimporter-23.04.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0
Requires: mailimporter-data = %{version}-%{release}
Requires: mailimporter-lib = %{version}-%{release}
Requires: mailimporter-license = %{version}-%{release}
Requires: mailimporter-locales = %{version}-%{release}
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : akonadi-mime-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : grantlee-dev
BuildRequires : grantleetheme-dev
BuildRequires : kcontacts-dev
BuildRequires : kimap-dev
BuildRequires : kimap-staticdev
BuildRequires : kmime-dev
BuildRequires : kpimtextedit-dev
BuildRequires : ktextaddons-dev
BuildRequires : pimcommon-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package data
Summary: data components for the mailimporter package.
Group: Data

%description data
data components for the mailimporter package.


%package dev
Summary: dev components for the mailimporter package.
Group: Development
Requires: mailimporter-lib = %{version}-%{release}
Requires: mailimporter-data = %{version}-%{release}
Provides: mailimporter-devel = %{version}-%{release}
Requires: mailimporter = %{version}-%{release}

%description dev
dev components for the mailimporter package.


%package lib
Summary: lib components for the mailimporter package.
Group: Libraries
Requires: mailimporter-data = %{version}-%{release}
Requires: mailimporter-license = %{version}-%{release}

%description lib
lib components for the mailimporter package.


%package license
Summary: license components for the mailimporter package.
Group: Default

%description license
license components for the mailimporter package.


%package locales
Summary: locales components for the mailimporter package.
Group: Default

%description locales
locales components for the mailimporter package.


%prep
%setup -q -n mailimporter-23.04.0
cd %{_builddir}/mailimporter-23.04.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1682104458
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1682104458
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mailimporter
cp %{_builddir}/mailimporter-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/mailimporter/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/mailimporter/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/mailimporter/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/mailimporter/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/mailimporter/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/mailimporter/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/mailimporter/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/mailimporter-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/mailimporter/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/mailimporter-%{version}/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/mailimporter/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
pushd clr-build
%make_install
popd
%find_lang libmailimporter

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qlogging-categories5/mailimporter.categories
/usr/share/qlogging-categories5/mailimporter.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KPim5/MailImporter/MailImporter/FilterBalsa
/usr/include/KPim5/MailImporter/MailImporter/FilterClawsMail
/usr/include/KPim5/MailImporter/MailImporter/FilterEvolution
/usr/include/KPim5/MailImporter/MailImporter/FilterEvolution_v2
/usr/include/KPim5/MailImporter/MailImporter/FilterEvolution_v3
/usr/include/KPim5/MailImporter/MailImporter/FilterIcedove
/usr/include/KPim5/MailImporter/MailImporter/FilterImporterBase
/usr/include/KPim5/MailImporter/MailImporter/FilterInfo
/usr/include/KPim5/MailImporter/MailImporter/FilterInfoGui
/usr/include/KPim5/MailImporter/MailImporter/FilterKMailArchive
/usr/include/KPim5/MailImporter/MailImporter/FilterKMail_maildir
/usr/include/KPim5/MailImporter/MailImporter/FilterLNotes
/usr/include/KPim5/MailImporter/MailImporter/FilterMBox
/usr/include/KPim5/MailImporter/MailImporter/FilterMailApp
/usr/include/KPim5/MailImporter/MailImporter/FilterMailmanGzip
/usr/include/KPim5/MailImporter/MailImporter/FilterOE
/usr/include/KPim5/MailImporter/MailImporter/FilterOpera
/usr/include/KPim5/MailImporter/MailImporter/FilterPMail
/usr/include/KPim5/MailImporter/MailImporter/FilterPlain
/usr/include/KPim5/MailImporter/MailImporter/FilterSeaMonkey
/usr/include/KPim5/MailImporter/MailImporter/FilterSylpheed
/usr/include/KPim5/MailImporter/MailImporter/FilterTheBat
/usr/include/KPim5/MailImporter/MailImporter/FilterThunderbird
/usr/include/KPim5/MailImporter/MailImporter/Filters
/usr/include/KPim5/MailImporter/MailImporter/ImportMailsWidget
/usr/include/KPim5/MailImporter/MailImporter/MailImporter_Utils
/usr/include/KPim5/MailImporter/MailImporter/MessageStatus
/usr/include/KPim5/MailImporter/MailImporter/OtherMailerUtil
/usr/include/KPim5/MailImporter/mailimporter/filterbalsa.h
/usr/include/KPim5/MailImporter/mailimporter/filterclawsmail.h
/usr/include/KPim5/MailImporter/mailimporter/filterevolution.h
/usr/include/KPim5/MailImporter/mailimporter/filterevolution_v2.h
/usr/include/KPim5/MailImporter/mailimporter/filterevolution_v3.h
/usr/include/KPim5/MailImporter/mailimporter/filtericedove.h
/usr/include/KPim5/MailImporter/mailimporter/filterimporterbase.h
/usr/include/KPim5/MailImporter/mailimporter/filterinfo.h
/usr/include/KPim5/MailImporter/mailimporter/filterinfogui.h
/usr/include/KPim5/MailImporter/mailimporter/filterkmail_maildir.h
/usr/include/KPim5/MailImporter/mailimporter/filterkmailarchive.h
/usr/include/KPim5/MailImporter/mailimporter/filterlnotes.h
/usr/include/KPim5/MailImporter/mailimporter/filtermailapp.h
/usr/include/KPim5/MailImporter/mailimporter/filtermailmangzip.h
/usr/include/KPim5/MailImporter/mailimporter/filtermbox.h
/usr/include/KPim5/MailImporter/mailimporter/filteroe.h
/usr/include/KPim5/MailImporter/mailimporter/filteropera.h
/usr/include/KPim5/MailImporter/mailimporter/filterplain.h
/usr/include/KPim5/MailImporter/mailimporter/filterpmail.h
/usr/include/KPim5/MailImporter/mailimporter/filters.h
/usr/include/KPim5/MailImporter/mailimporter/filterseamonkey.h
/usr/include/KPim5/MailImporter/mailimporter/filtersylpheed.h
/usr/include/KPim5/MailImporter/mailimporter/filterthebat.h
/usr/include/KPim5/MailImporter/mailimporter/filterthunderbird.h
/usr/include/KPim5/MailImporter/mailimporter/importmailswidget.h
/usr/include/KPim5/MailImporter/mailimporter/mailimporter_export.h
/usr/include/KPim5/MailImporter/mailimporter/mailimporter_utils.h
/usr/include/KPim5/MailImporter/mailimporter/messagestatus.h
/usr/include/KPim5/MailImporter/mailimporter/othermailerutil.h
/usr/include/KPim5/MailImporter/mailimporter_version.h
/usr/include/KPim5/MailImporterAkonadi/MailImporterAkonadi/FilterImporterAkonadi
/usr/include/KPim5/MailImporterAkonadi/mailimporterakonadi/filterimporterakonadi.h
/usr/include/KPim5/MailImporterAkonadi/mailimporterakonadi/mailimporterakonadi_export.h
/usr/include/KPim5/MailImporterAkonadi/mailimporterakonadi_version.h
/usr/lib64/cmake/KF5MailImporter/KF5MailImporterConfig.cmake
/usr/lib64/cmake/KF5MailImporter/KF5MailImporterConfigVersion.cmake
/usr/lib64/cmake/KF5MailImporterAkonadi/KF5MailImporterAkonadiConfig.cmake
/usr/lib64/cmake/KF5MailImporterAkonadi/KF5MailImporterAkonadiConfigVersion.cmake
/usr/lib64/cmake/KF5MailImporterAkonadi/KPim5MailImporterAkonadiTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5MailImporterAkonadi/KPim5MailImporterAkonadiTargets.cmake
/usr/lib64/cmake/KPim5MailImporter/KPim5MailImporterConfig.cmake
/usr/lib64/cmake/KPim5MailImporter/KPim5MailImporterConfigVersion.cmake
/usr/lib64/cmake/KPim5MailImporter/KPim5MailImporterTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim5MailImporter/KPim5MailImporterTargets.cmake
/usr/lib64/cmake/KPim5MailImporterAkonadi/KPim5MailImporterAkonadiConfig.cmake
/usr/lib64/cmake/KPim5MailImporterAkonadi/KPim5MailImporterAkonadiConfigVersion.cmake
/usr/lib64/cmake/KPim5MailImporterAkonadi/KPim5MailImporterAkonadiTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim5MailImporterAkonadi/KPim5MailImporterAkonadiTargets.cmake
/usr/lib64/libKPim5MailImporter.so
/usr/lib64/libKPim5MailImporterAkonadi.so
/usr/lib64/qt5/mkspecs/modules/qt_MailImporter.pri
/usr/lib64/qt5/mkspecs/modules/qt_MailImporterAkonadi.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKPim5MailImporter.so.5
/usr/lib64/libKPim5MailImporter.so.5.23.0
/usr/lib64/libKPim5MailImporterAkonadi.so.5
/usr/lib64/libKPim5MailImporterAkonadi.so.5.23.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mailimporter/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/mailimporter/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/mailimporter/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/mailimporter/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/mailimporter/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4
/usr/share/package-licenses/mailimporter/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/mailimporter/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/mailimporter/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f libmailimporter.lang
%defattr(-,root,root,-)

